### ISSUE TITLE
增加一个消息通知模版系统，可以支持在策略中填写通知模版，变量引用

### ISSUE THREAD

**Issue by IMBlues** [TencentBlueKing/bk-honor#3]
举个例子

```yaml
- name: "初审"
     steps:
        - type: "approval"
          auto_execute: true
          name: "初审"
          approver_groups: ["award_liaison"]
          allow_operations: ["approve", "reject", "recommend"]
          broadcast:
            content_tmpl:
              approve: "恭喜 {{ _user_groups.applicant }}，你的{{ _policy.name }}已经通过{{ _stage.name }}，并进入专业评审环节"
              reject: "很遗憾，你的{{ _policy.name }}申报没有通过{{ _stage.name }}，请再接再厉"
              recommend: "经过评估，建议项目转申报其他奖项"
```
